### ISSUE TITLE
RuntimeError: the derivative for 'indices' is not implemented

### ISSUE THREAD

**Issue by ritvikagrawal1** [facebookresearch/Listen-to-Look#12]
```
python3 main.py --train_dataset_file /scratch/supreeth/listen_to_look/listen_to_look/train.pkl --test_dataset_file /scratch/supreeth/listen_to_look/listen_to_look/val.pkl --batch_size 32 --warmup_epochs 0 --epochs 25 --lr 0.01 --milestones 15 20 --momentum 0.9 --decode_threads 4 --scheduler --num_classes 200 --weights_audioImageModel /scratch/supreeth/listen_to_look/listen_to_look/ImageAudioNet_ActivityNet.pth --checkpoint_freq 10 --episode_length 10 --checkpoint_path /scratch/supreeth/listen_to_look/checkpoints/exp --freeze_imageAudioNet --with_avgpool_ce_loss --compute_mAP --mean_feature_as_start --subsample_factor 1 --with_replacement |& tee -a /scratch/supreeth/listen_to_look/logs/exp.log
2022-06-26 03:27:13,267 main: 43: DEBUG:: Namespace(avgpool_ce_loss_weight=1, batch_size=32, checkpoint_freq=10, checkpoint_path='/scratch/supreeth/listen_to_look/checkpoints/exp', compute_mAP=True, decode_threads=4, episode_length=10, epochs=25, feature_interpolate=False, feature_subsample=False, freeze_imageAudioNet=True, gt_feature_eval=False, hidden_size=512, lr=0.01, lstm_ce_loss_weight=1, mean_feature_as_start=True, milestones=[15, 20], momentum=0.9, num_classes=200, pretrained_model=None, print_freq=20, scheduler=True, start_epoch=0, subsample_factor=1, test_dataset_file='/scratch/supreeth/listen_to_look/listen_to_look/val.pkl', train_dataset_file='/scratch/supreeth/listen_to_look/listen_to_look/train.pkl', visualization=False, warmup_epochs=0, weight_decay=0.0001, weights_audioImageModel='/scratch/supreeth/listen_to_look/listen_to_look/ImageAudioNet_ActivityNet.pth', with_avgpool_ce_loss=True, with_lstm_ce_loss=False, with_replacement=True)
epoch,loss,acc,lr
Loading the weights for imageAudioClassifier network
2022-06-26 03:27:18,624 data: 30: DEBUG:: Time to load paths: 0.006342887878417969
2022-06-26 03:27:18,624 data: 31: DEBUG:: Number of videos: 9511
2022-06-26 03:27:18,627 data: 30: DEBUG:: Time to load paths: 0.0027451515197753906
2022-06-26 03:27:18,627 data: 31: DEBUG:: Number of videos: 4659
2022-06-26 03:27:18,629 main: 131: DEBUG:: DataParallel(
  (module): AudioPreviewModel(
    (net_imageAudio): ImageAudioModel(
      (imageAudio_fc1): Linear(in_features=1024, out_features=1024, bias=True)
      (imageAudio_fc2): Linear(in_features=1024, out_features=512, bias=True)
    )
    (net_classifier): ClassifierNet(
      (classifier): Linear(in_features=512, out_features=200, bias=True)
    )
    (image_queryfeature_mlp): Sequential(
      (0): Linear(in_features=1024, out_features=1024, bias=True)
      (1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Linear(in_features=1024, out_features=512, bias=True)
    )
    (audio_queryfeature_mlp): Sequential(
      (0): Linear(in_features=1024, out_features=1024, bias=True)
      (1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Linear(in_features=1024, out_features=512, bias=True)
    )
    (prediction_fc): Linear(in_features=1024, out_features=200, bias=True)
    (image_key_conv1x1): Sequential(
      (0): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))
      (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (audio_key_conv1x1): Sequential(
      (0): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))
      (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (rnn): LSTMCell(512, 1024)
    (modality_attention): Linear(in_features=1024, out_features=2, bias=True)
    (softmax): Softmax(dim=-1)
  )
)
2022-06-26 03:27:18,629 main: 141: DEBUG:: Entering the training loop
Traceback (most recent call last):
  File "main.py", line 158, in <module>
    main(args)
  File "main.py", line 148, in main
    logger, epoch_logger=epoch_log, checkpointer=checkpointer, writer=writer)
  File "/home/supreeth_s_karan/Listen-to-Look/train.py", line 39, in train_epoch
    predictions, selected_imageAudioFeatures, selected_step_predictions = model.forward(image_features, audio_features, feature_masks, args.episode_length)
  File "/home/supreeth_s_karan/supreeth_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/supreeth_s_karan/supreeth_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/supreeth_s_karan/supreeth_env/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/supreeth_s_karan/supreeth_env/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/supreeth_s_karan/supreeth_env/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/supreeth_s_karan/supreeth_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/supreeth_s_karan/Listen-to-Look/models/audioPreview_model.py", line 159, in forward
    helper_tensor[torch.LongTensor(range(self.batch_size)), image_feature_indexes_next] = 0 #change to 0 of indexed positions
RuntimeError: the derivative for 'indices' is not implemented
```

**Comment by ritvikagrawal1** [comment]
@likethesky @Celebio @colesbury @pdollar 
Can you please help in rectification of this error?
